### PR TITLE
Feature/js make docker container

### PR DESCRIPTION
**Pull request by NerdsvilleCEO**
This depends on #34 once we get that one merged up with #33 changes this will be test-able

### CODE REVIEW

**Comment by jnimety** [comment]
@NerdsvilleCEO the yarn work is merged

**Comment by treznick** [comment]
@NerdsvilleCEO feel free to rebase and merge

**Comment by treznick** [comment]
but also @NerdsvilleCEO maybe add something to the `README` for how to use this with Docker? Not everyone (read: me) is a docker expert (read: I have no idea about how to docker)

**Comment by NerdsvilleCEO** [comment]
@treznick I am going to take a look at this today I didn't get the notifications until just now

**Comment by NerdsvilleCEO** [comment]
Will get these docs made today @treznick apologies for the delay this week has been crazy

**Comment by treznick** [comment]
@NerdsvilleCEO no worries! we all have our day jobs, and our night jobs fighting crime in masks and capes

**Comment by treznick** [comment]
@NerdsvilleCEO We had to change the merge base branch from master to develop, and so can you confirm whether this work is still good and rebase on develop?

**Pull request closed without merging**
