### PR TITLE
Refactor Meetup.com codebase

### PR DESCRIPTION
**Pull request by sukima**
Oh boy this was a doozy. Sorry it took so long but work and family kept getting in the way.

Coming from Ember.JS (and this is probubly true for Angular devs too) the push to components for rendering part of a page is quite prominent. Much of Ember is trying to close the gap between the web components standard and the do-it-yourself frameworks.

Using those ideals it seemed appropriate to look into the web component standard. The concepts were perfect for the problem domain on the website. So I dove in. I wanted to have a safety net so I also worked on developing a test suite.

After it was all done I also looked into a way to search for developers. Sadly though the Meetup API does not support text searching members.

Another edge case I found was that the paginator (even the original one) doesn't scale well when you get enough members to cause the list to wrap to the next line. Perhaps a new paginator design would help or maybe some fancy flexbox work. If anyone has thoughts on this perhaps we can discuss it here.

### CODE REVIEW

**Comment by maxx1128** [comment]
Looks and works great! Understandable that you had other priorities before getting to it. The only issue I see is the mobile menu isn't opening for some reason. There was a jQuery-related error in the console that's likely connected, is below.

```
TypeError: a.getAttribute is not a function
```

Once that's set and the mobile menu is fixed then it'll be good to merge. As for the paginator and general layout, I can add some flexbox later on so it handles better on mobile and other screen sizes.

**Comment by kljensen** [comment]
👏👏

**Comment by sukima** [comment]
@maxx1128 I am unable to reproduce this error on commit 9f7b25485f9cdc4069abc4df1bef3d4bb6f48a11. Can you help diagnose this?

nhio-no-error

**Comment by maxx1128** [comment]
Looks like it's only happening on Firefox for me. Not sure if this is only because it's being run locally, took a shot of the error messages below.

screen shot 2016-08-09 at 8 27 08 am

**Comment by sukima** [comment]
@maxx1128 Again I can't seem to make this happen. Really sorry.

newhavenio-firefox

_(FireFox is slow when dev tools are open. Oh FireFox.)_

**Comment by treznick** [comment]
@max1128 are you running any browser plugins that maybe would be
interfering with things? Does this still work in a clean Firefox?

**Comment by maxx1128** [comment]
Cleaned out Firefox but is still occuring. @sukima was it still working on your firefox when you tried the mobile menu?

If it's only my Firefox having an issue here though, I say we merge anyway. I'd only say we need to resolve it if it's on all Firefox browsers. But if the menu is working on Firefox for everyone else then I'm good to merge.

**Comment by treznick** [comment]
@sukima @max1128 I'm able to replicate it locally.

@sukima, let's look at this tomorrow morning.

**Comment by sukima** [comment]
Ok I found it. Took a while sorry 'bout that. https://github.com/webcomponents/webcomponentsjs/issues/49

Will look into a fix…

**Comment by sukima** [comment]
@maxx1128 Try it now.

**Comment by maxx1128** [comment]
It's now working for me! Will merge it later today.

**Comment by sukima** [comment]
Boom that's how its done Chuck Noris style

**Comment by treznick** [comment]
🎉

**Comment by treznick** [comment]
:tada:

**Pull request merged**
