### PR TITLE
New post/node newsletter

### PR DESCRIPTION
**Pull request by maxx1128**
New blog post, this is an external link to a post I wrote on dev.to about using Node and the Twitter API to create my own custom newsletter.

### CODE REVIEW

**Comment by danbernier** [comment]
Huh. Curious, how will this display on the blog? I'm guessing it'll be an entry on [the index](http://newhaven.io/blog/), that links to `https://dev.to/maxwell_dev/how-to-make-an-anime-newsletter`?

**Comment by maxx1128** [comment]
Sorry for late response, but that's basically how it would. It'll look the same but have an icon next to the title to show it's an external blog post. It'll open in a new tab to that URL.

**Comment by danbernier** [comment]
Ah, no worries. I'm a fan of this, then! :shipit:

**Comment by maxx1128** [comment]
Awesome! Yeah it was put in originally so we could still share posts here we'd put on other sites.

Anyways I'll go ahead and merge.

**Pull request merged**
