### PR TITLE
Update icon to use large icon - Redux

### PR DESCRIPTION
**Pull request by treznick**
Reverts newhavenio/newhavenio.github.io#35

### CODE REVIEW

**Comment by NerdsvilleCEO** [comment]
@treznick approved pending rebase

**Comment by sukima** [comment]
@treznick, @NerdsvilleCEO I have rebased this **and** added a commit that will show the large slack button using the webcomponent.

**Comment by NerdsvilleCEO** [comment]
@sukima cool I'll test this in a bit

**Comment by NerdsvilleCEO** [comment]
@sukima this is looking good but I want to see if we can get the two issues mentioned on #56 I will message you on slack

**Comment by treznick** [comment]
I leave it to youse guys to do this one 😸

**Comment by treznick** [comment]
@NerdsvilleCEO we changed the merge base branch on PRs from master to develop, and I'm going through and modifying all PRs. Can you confirm whether or not this work is still good?

**Comment by NerdsvilleCEO** [comment]
@sukima I think you had previously fixed the issue, I'd be in favor of closing this PR and making a new one if any changes are needed... we can pair on this whenever

Thanks!

**Pull request closed without merging**
