### PR TITLE
Improve Development Environment

### PR DESCRIPTION
**Pull request by jnimety**
* Migrate from Bower to Yarn
* Add a `Gemfile` with github pages / jekyll dependencies
* Add `.ruby-*` files for ruby env management
* Update README

### CODE REVIEW

**Comment by jnimety** [comment]
@maxx1128 @treznick Would love your feedback, thanks!

**Comment by jnimety** [comment]
I added jquery to package.json and just noticed that there are a number of js libs installed directly in the `js/` directory. We should manage those via yarn if possible so I'll add them. @maxx1128 I'm assuming your build script will then copy them into `js/`

**Comment by jnimety** [comment]
bump

**Comment by sukima** [comment]
If we are using Yarn doesn't that remove the need to commit the entire `node_modules`? I though Yarn was deterministic with the `yarn.lock` file.

**Comment by jnimety** [comment]
Yes!

**Comment by kljensen** [comment]
The latest npm has a deterministic lock too.

**Comment by jnimety** [comment]
I have no opinion re: yarn vs npm lock, thoughts?

**Comment by jnimety** [comment]
`node_modules` removed

**Comment by sukima** [comment]
I still find Yarn more aesthetic though feature wise the two are now on par.

**Comment by kljensen** [comment]
Npm is more common. I tend use yarn. Yarn tends to be installed by npm, but
the recommend using the OS package manager now.

I don't feel it matters in this context.

**Comment by treznick** [comment]
```ruby
2.4.2 :002 > %i(yarn npm).sample
=> :yarn
```

ruby has spoken. yarn it is!
(with apologies to @kljensen for using ruby instead of python)

**Comment by NerdsvilleCEO** [comment]
@jnimety can you rebase to my branch, I did some similar changes :) I like how you lock a ruby version above 2.4.2 to mitigate this https://www.ruby-lang.org/en/news/2017/08/29/multiple-vulnerabilities-in-rubygems/ as well as some other changes which aren't in my PR.

**Comment by jnimety** [comment]
superseded by #42

**Pull request closed without merging**
