### PR TITLE
moved bourbon and susy to regular dependencys

### PR DESCRIPTION
**Pull request by bsutt123**
Bourbon and Susy are both referend in `main.scss` and Travis was complaining that it didn't have them, so I moved them to regular dependencies.

If someone who knows more about travis knows that it needs/doesn't need webpack in the regular dependencies, then I can move that as necessary as well.

### CODE REVIEW

**Comment by bsutt123** [comment]
@NerdsvilleCEO So we got a build failure because we had some dependencies in devDeps that needed to be in dependencies (It was bourbon and susy which get imported with sass).

I moved those up, but I'm wondering if you know if TravisCI needs us to include webpack or babel or some of the other devDeps in regular Deps so that it will be able to install them and run the build process.

**Comment by jnimety** [comment]
travis should do whatever we tell it to do, so maybe just tell it to install dev dependencies since they're required for the build step? @NerdsvilleCEO and @treznick please weigh in since you set that up.

**Comment by treznick** [comment]
@jnimety @bsutt123 we can test that assumption by removing the dev
dependencies and seeing if it builds in a PR. I'll do that

**Comment by jnimety** [comment]
maybe in `build.sh` we need a `yarn install`?

**Comment by jnimety** [comment]
it makes perfect sense that you need dev deps to build/deploy, so we just need to figure out where to have travis install them.

**Comment by jnimety** [comment]
thanks @treznick !

**Comment by treznick** [comment]
see #77

**Comment by treznick** [comment]
FWIW travis will run `yarn` if it sees a `yarn.lock` in the repo
https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Travis-CI-supports-yarn

**Comment by treznick** [comment]
so I think we can just merge this. merging

**Comment by jnimety** [comment]
Why is yarn install not installing dev deps?

**Comment by treznick** [comment]
@jnimety it is. the problem isn't that the build script isn't doing that, and bourbon and susy were listed as devDependencies

The new problem is that our references to `bourbon` were looking in `node_modules`. I _think_ there's a webpack configuration option to deal with this.

**Comment by bsutt123** [comment]
Of course, I checked all the html and css but didn't check the node_modules references that were there before I switched us over to yarn.

I think that we can require stylesheets with `require('susy/bootstrap/...`) in the entry,js file. We might need to modify the webpack configu to have a sass loader for us, but that shouldn't be too hard.

I'll work on this once I get back into town on Wednesday if it isn't worked out by then.

**Pull request merged**
