### PR TITLE
Tailwind redesign

### PR DESCRIPTION
**Pull request by maxx1128**
This is a large redesign that aims to obliterate our current front-end and:

* Replace Bootstrap and other dependencies with TailwindCSS
* Make it accessible by complying to the WCAG 2.0 AA guidelines

### CODE REVIEW

**Comment by maxx1128** [comment]
screen shot 2019-01-24 at 10 39 31 am
screen shot 2019-01-24 at 10 39 37 am
screen shot 2019-01-24 at 10 40 04 am
screen shot 2019-01-24 at 10 42 10 am
screen shot 2019-01-24 at 10 42 23 am

**Comment by maxx1128** [comment]
Currently still needs to add some more content to the homepage, so any feedback on additional content or photos for that is most appreciated.

**Comment by Quinncuatro** [comment]
Forgot to make a note actually ON the PR.

Looks good! I'd keep the two card width rows for the events section.

Only thing I'd change is to make sure we have the "Join our Slack" button big and front and center. It's a big value add to be able to toss people directly into the mix.

**Comment by Quinncuatro** [comment]
Only thing I'm really concerned about (besides the Slack button) is that it looks a little underdesigned (if that's a word). I know the goal was to make it more accessible, but at least Steve and I thought that it looks a little bland, and maybe off brand? More than happy letting you take the reigns on what a fix for that might be. Even if it's just adding some more orange/charcoal (current design).

Also, can we do something with the social links? Maybe make them look more like buttons or add the relevant icons? That bit just looks a little underdesigned as well.

**Pull request closed without merging**
