### PR TITLE
Convert slack button to a web component

### PR DESCRIPTION
**Pull request by sukima**
This will show a loading button while the IFRAME spins up the Heroku app. When complete it replaces the loading button with the IFRAME.

### CODE REVIEW

**Comment by sukima** [comment]
If anyone has some SVG magic let me know. The current loading button is an animated GIF but it could be something else (like an animated SVG). I attempted to optimize it in The GIMP best I could. Ended up constructing most of it myself (Slack does not appear to have an official loading button).

**Comment by treznick** [comment]
@danbernier you know a thing or two about SVGs, no?

**Comment by danbernier** [comment]
I know a thing or two about SVGs, yes, but not how to animate them. Just ship the .gif.

**Comment by jnimety** [comment]
ship it!

**Pull request merged**
